
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu May 26 21:22:08 CST 2022
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 4;
  public static final int CorcheteApertura = 22;
  public static final int For = 7;
  public static final int Suma = 14;
  public static final int Numero = 31;
  public static final int Comentario = 29;
  public static final int Incrementar = 25;
  public static final int ComillaDoble = 13;
  public static final int LlaveCierre = 21;
  public static final int LlaveApertura = 20;
  public static final int ParentesisApertura = 18;
  public static final int ERROR = 32;
  public static final int Break = 11;
  public static final int Identificador = 30;
  public static final int Expr = 27;
  public static final int Int = 2;
  public static final int Default = 10;
  public static final int Comparacion = 28;
  public static final int Main = 24;
  public static final int CorcheteCierre = 23;
  public static final int EOF = 0;
  public static final int Division = 17;
  public static final int Proc = 33;
  public static final int Resta = 15;
  public static final int Puts = 8;
  public static final int If = 3;
  public static final int Return = 34;
  public static final int error = 1;
  public static final int Switch = 9;
  public static final int While = 5;
  public static final int Multiplicacion = 16;
  public static final int Punto_coma = 26;
  public static final int SaltoLinea = 12;
  public static final int ParentesisCierre = 19;
  public static final int DeclaracionVariable = 6;
}

